spring:
  datasource:
    url: jdbc:postgresql://localhost/schichtplaner
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update

graphql:
  packages:
    - "com.felixhoner.schichtplaner.api.graphql"
